services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: bpm-rabbitmq
    expose:
      - "5672"
      - "15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - bpm-network

  zipkin:
    image: openzipkin/zipkin
    container_name: bpm-zipkin
    expose:
      - "9411"
    networks:
      - bpm-network

  prometheus:
    image: prom/prometheus
    container_name: bpm-prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    expose:
      - "9090"
    networks:
      - bpm-network
    depends_on:
      - bpm-audit-service
      - bpm-compliance-service
      - bpm-gateway-service
      - bpm-main-service
      - bpm-onboarding-service
      - bpm-statistics-service
      - notification-service

  grafana:
    image: grafana/grafana
    container_name: bpm-grafana
    expose:
      - "3000"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      prometheus:
        condition: service_started
    networks:
      - bpm-network

  bpm-gateway-service:
    build:
      context: .
      dockerfile: ./bpm-gateway-service/Dockerfile
    container_name: bpm-gateway-service
    ports:
      - "8081:8081"
    environment:
      - MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http://zipkin:9411/api/v2/spans
    depends_on:
      - bpm-audit-service
      - bpm-compliance-service
      - bpm-main-service
      - bpm-onboarding-service
      - bpm-statistics-service
      - notification-service
      - zipkin
    networks:
      - bpm-network
    restart: unless-stopped

  bpm-main-service:
    build:
      context: .
      dockerfile: ./bpm-main-service/Dockerfile
    container_name: bpm-main-service
    expose:
      - "8080"
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest
      - GRPC_ONBOARDING_ADDRESS=static://bpm-onboarding-service:9091
      - MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http://zipkin:9411/api/v2/spans
    depends_on:
      rabbitmq:
        condition: service_healthy
      zipkin:
        condition: service_started
    networks:
      - bpm-network
    restart: unless-stopped

  bpm-audit-service:
    build:
      context: .
      dockerfile: ./bpm-audit-service/Dockerfile
    container_name: bpm-audit-service
    expose:
      - "8082"
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest
      - MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http://zipkin:9411/api/v2/spans
    depends_on:
      rabbitmq:
        condition: service_healthy
      zipkin:
        condition: service_started
    networks:
      - bpm-network
    restart: unless-stopped

  bpm-statistics-service:
    build:
      context: .
      dockerfile: ./bpm-statistics-service/Dockerfile
    container_name: bpm-statistics-service
    expose:
      - "8083"
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest
      - MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http://zipkin:9411/api/v2/spans
    depends_on:
      rabbitmq:
        condition: service_healthy
      zipkin:
        condition: service_started
    networks:
      - bpm-network
    restart: unless-stopped

  bpm-compliance-service:
    build:
      context: .
      dockerfile: ./bpm-compliance-service/Dockerfile
    container_name: bpm-compliance-service
    expose:
      - "8085"
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest
      - MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http://zipkin:9411/api/v2/spans
    depends_on:
      rabbitmq:
        condition: service_healthy
      zipkin:
        condition: service_started
    networks:
      - bpm-network
    restart: unless-stopped

  notification-service:
    build:
      context: .
      dockerfile: ./notification-service/Dockerfile
    container_name: notification-service
    expose:
      - "8086"
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest
      - MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http://zipkin:9411/api/v2/spans
    depends_on:
      rabbitmq:
        condition: service_healthy
      zipkin:
        condition: service_started
    networks:
      - bpm-network
    restart: unless-stopped

  bpm-onboarding-service:
    build:
      context: .
      dockerfile: ./bpm-onboarding-service/Dockerfile
    container_name: bpm-onboarding-service
    expose:
      - "8084"
      - "9091"
    environment:
      - MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http://zipkin:9411/api/v2/spans
    depends_on:
      zipkin:
        condition: service_started
    networks:
      - bpm-network
    restart: unless-stopped

networks:
  bpm-network:
    driver: bridge

volumes:
  rabbitmq_data:
