spring.application.name=bpm-gateway-service
server.port=8081
spring.main.web-application-type=reactive
server.http2.enabled=true
spring.cloud.gateway.httpclient.http2=true
spring.cloud.compatibility-verifier.enabled=false

spring.cloud.gateway.routes[0].id=notifications-ws
spring.cloud.gateway.routes[0].uri=ws://notification-service:8086
spring.cloud.gateway.routes[0].predicates[0]=Path=/ws/notifications

spring.cloud.gateway.routes[1].id=notifications-rest
spring.cloud.gateway.routes[1].uri=http://notification-service:8086
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/notifications/**

spring.cloud.gateway.routes[2].id=main-rest
spring.cloud.gateway.routes[2].uri=http://bpm-main-service:8080
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/**

spring.cloud.gateway.routes[3].id=main-graphql
spring.cloud.gateway.routes[3].uri=http://bpm-main-service:8080
spring.cloud.gateway.routes[3].predicates[0]=Path=/graphql,/graphiql,/schema.json

spring.cloud.gateway.routes[4].id=compliance-rest
spring.cloud.gateway.routes[4].uri=http://bpm-compliance-service:8085
spring.cloud.gateway.routes[4].predicates[0]=Path=/compliance/**

spring.cloud.gateway.routes[5].id=audit-rest
spring.cloud.gateway.routes[5].uri=http://bpm-audit-service:8082
spring.cloud.gateway.routes[5].predicates[0]=Path=/audit/**

spring.cloud.gateway.routes[6].id=statistics-rest
spring.cloud.gateway.routes[6].uri=http://bpm-statistics-service:8083
spring.cloud.gateway.routes[6].predicates[0]=Path=/statistics/**

spring.cloud.gateway.routes[7].id=onboarding-grpc
spring.cloud.gateway.routes[7].uri=http://bpm-onboarding-service:9091
spring.cloud.gateway.routes[7].predicates[0]=Path=/OnboardingService/**,/grpc.reflection.v1alpha.ServerReflection/**,/grpc.health.v1.Health/**
spring.cloud.gateway.routes[7].filters[0]=SetRequestHeader=content-type,application/grpc

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.tracing.sampling.probability=1.0
management.zipkin.tracing.endpoint=http://zipkin:9411/api/v2/spans
management.metrics.export.prometheus.enabled=true
